version: '3.3'

services:
  list_server:
    build: .
    image: list_server
    container_name: list_server
    restart: always
    volumes:
      - type: bind
          source: ./
          target: /app
          volume:
            nocopy: true
    env_file: .env
    command: npm start # start status server
    expose:
        - 3000
    ports: 
        - "3000:3000"