version: '3.9'

services:
  mongo:
    image: mongo
    container_name: user_management_mongo
    restart: always
    volumes:
      - type: bind
        source: ./db/mongo
        target: /data/db
        volume:
          nocopy: true
    logging:
      driver: none 
    networks:
      - user_management_net

  user_management_server:
    build: .
    image: user_management_server
    container_name: user_management_server
    restart: always
    volumes:
        - .:/app
        - /app/node_modules
    env_file: .env
    command: npm start # start status server
    expose:
        - 3030
    ports: 
        - "3030:3030"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - user_management_net

networks:
  user_management_net:
    name: user_management_net
    driver: bridge
